repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      exclude: 'templates'
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      exclude: 'templates'
      language_version: python3
