[3.3.4]
Title = "Version 3.3.4"
Description = [ "[Bug]: Duplicate README sections in ini files.",]
GitHubIssues = [ 23, 24,]

[3.3.2]
Title = "Version 3.3.2"
Description = [ "[Enhancement]: Generate README from template.", "- Extensive changes to the building of the README file.",]
GitHubIssues = [ 23, 24,]

[3.2.1]
Title = "Version 3.2.1"
Description = [ "Version 3.3.0", "[Bug]: Ignore git tags that are not versions.", "[Enhancement]: Add GitHubIssues to release.toml.",]
GitHubIssues = [ 21, 22,]

[3.2.0]
Title = "Version 3.2.0"
Description = [ "Version 3.1.10", "[Bug]: Loading of the target source code fails.",]
GitHubIssues = [ 19,]

[3.1.10]
Title = "Version 3.1.10"
Description = [ "[Bug]: pip install -e . fails.", "Discrepancy between import options from default packageit.ini and .packageit/packageit.ini.",]
GitHubIssues = [ 4, 18,]

[3.1.9]
Title = "Version 3.1.9"
Description = [ "[Bug]: Fix conftest.py, templ_test_package.py and templ_package.py",]
GitHubIssues = [ 16,]

[3.1.8]
Title = "Version 3.1.8"
Description = [ "[Bug]: PackageIt crash during the creation of a package due to issues in the templ_package.py",]
GitHubIssues = [ 14,]

[3.1.7]
Title = "Version 3.1.7"
Description = [ "[Enhancement]: Issues with templ_package.py", "- The renew_parameters() method is not necessary and an overkill for the establishment of a basic workable app.", "- The logger is instantiated twice i.e. not removed during a previous code change.",]
GitHubIssues = [ 15,]

[3.1.6]
Title = "Version 3.1.6"
Description = [ "[Bug]: Private repositories should not be published to PyPI and ReadTheDocs",]

[3.1.5]
Title = "Version 3.1.5"
Description = [ "Corrected some settings in the .ini files",]

[3.1.4]
Title = "Version 3.1.4"
Description = [ "Destination project sources code fails to load", "To be able to read the project description and title, the source code must be loaded to access the dunder methods. PackageIt assume a module name with he same name as the project. This is not always the case and it causes an exception. Handle the exception to rather load temporary values rather than crashing out.",]

[3.1.3]
Title = "Version 3.1.3"
Description = [ "Version 3.1.3", "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
